
#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE 16000
#define AUDIO_OUTPUT_SAMPLE_RATE 16000

#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_40
#define AUDIO_I2S_GPIO_WS GPIO_NUM_45
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_39
#define AUDIO_I2S_GPIO_DIN GPIO_NUM_38
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_48

#define AUDIO_CODEC_PA_PIN GPIO_NUM_46
#define AUDIO_CODEC_I2C_SDA_PIN GPIO_NUM_21
#define AUDIO_CODEC_I2C_SCL_PIN GPIO_NUM_47
#define AUDIO_CODEC_ES8311_ADDR ES8311_CODEC_DEFAULT_ADDR

#define BUILTIN_LED_GPIO GPIO_NUM_17

// QMI8658传感器I2C管脚配置
#define QMI8658_I2C_SDA_PIN GPIO_NUM_11
#define QMI8658_I2C_SCL_PIN GPIO_NUM_12

// 按键ADC管脚配置
#define BUTTON_ADC_PIN GPIO_NUM_9
#define BUTTON_ADC_CHANNEL 8  // GPIO_NUM_9对应ADC1_CHANNEL_8

#endif // _BOARD_CONFIG_H_
